# This file was generated by GoReleaser. DO NOT EDIT.
cask "ace-dt" do
  desc "A CLI tool for packaging, uploading, and downloading data from OCI registries."
  homepage "https://github.com/act3-ai/data-tool"
  version "1.16.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ace-dt"

  on_macos do
    on_intel do
      url "https://github.com/act3-ai/data-tool/releases/download/v1.16.1/ace-dt-v1.16.1-darwin-amd64.tar.gz",
        using: :homebrew_curl
      sha256 "564aa2ccb73aaadef2b41a60fd84f06ce56dd76cf703737fe0c2e14389878e01"
    end
    on_arm do
      url "https://github.com/act3-ai/data-tool/releases/download/v1.16.1/ace-dt-v1.16.1-darwin-arm64.tar.gz",
        using: :homebrew_curl
      sha256 "f57a800cbcb435a7131300c22759ffa3b53609135fdb9e784f5752359f630445"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/act3-ai/data-tool/releases/download/v1.16.1/ace-dt-v1.16.1-linux-amd64.tar.gz",
        using: :homebrew_curl
      sha256 "62868d504309fe01f5c44cdea04b73be7136d763cec7130aed2c801f76ea7187"
    end
    on_arm do
      url "https://github.com/act3-ai/data-tool/releases/download/v1.16.1/ace-dt-v1.16.1-linux-arm64.tar.gz",
        using: :homebrew_curl
      sha256 "fd6ee80b24dbc59df6d3d2d6bc488b9852808a5c5fd84f73ffdd27c1a5095a8b"
    end
  end

  conflicts_with formula: [
      "ace-dt",
    ]

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ace-dt"]
    end
    generate_completions_from_executable(bin/"ace-dt", "completion")
    mkdir "man" do
      system bin/"ace-dt", "gendocs", "man", "."
      man1.install Dir["*.1"]
    end
    system "#{bin}/ace-dt version"
  end

  uninstall delete: [
      "~/.cache/ace/dt/",
    ]

  # No zap stanza required
end
