# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AceDt < Formula
  desc "A CLI tool for packaging, uploading, and downloading data from OCI registries."
  homepage "https://github.com/act3-ai/data-tool"
  version "1.15.30"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/act3-ai/data-tool/releases/download/v1.15.30/ace-dt-v1.15.30-darwin-amd64.tar.gz"
      sha256 "ef704553923d2a164ee3f8f927f690babe00dd39711e8ba3e60cfddb55630eb6"

      def install
        bin.install ace-dt
        generate_completions_from_executable(bin/"ace-dt", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"ace-dt", "gendocs", "man", "."
          man1.install Dir["*.1"]
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/act3-ai/data-tool/releases/download/v1.15.30/ace-dt-v1.15.30-darwin-arm64.tar.gz"
      sha256 "20c113284859948a595a9dad7ce0b99e570205c7bc55d0984643a4f3522a0596"

      def install
        bin.install ace-dt
        generate_completions_from_executable(bin/"ace-dt", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"ace-dt", "gendocs", "man", "."
          man1.install Dir["*.1"]
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/data-tool/releases/download/v1.15.30/ace-dt-v1.15.30-linux-amd64.tar.gz"
        sha256 "77d14a579b21d88268c6dff5eb4087290f2d211b22a6582fc0ab753ed825a45a"

        def install
          bin.install ace-dt
          generate_completions_from_executable(bin/"ace-dt", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"ace-dt", "gendocs", "man", "."
            man1.install Dir["*.1"]
          end
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/data-tool/releases/download/v1.15.30/ace-dt-v1.15.30-linux-arm64.tar.gz"
        sha256 "dfd3d919d7a6a1fb2146ecb6722d6572ce44ba311eea7811f230af6dda80d122"

        def install
          bin.install ace-dt
          generate_completions_from_executable(bin/"ace-dt", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"ace-dt", "gendocs", "man", "."
            man1.install Dir["*.1"]
          end
        end
      end
    end
  end

  test do
    system "#{bin}/ace-dt version"
  end
end
