# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AceDt < Formula
  desc "A CLI tool for packaging, uploading, and downloading data from OCI registries."
  homepage "https://github.com/act3-ai/data-tool"
  version "1.15.32"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/act3-ai/data-tool/releases/download/v1.15.32/ace-dt-v1.15.32-darwin-amd64.tar.gz"
      sha256 "ad1ed32917cbd4c8daba3771c3baa5a3cf5fd976da943454efb5749be8e65dca"

      def install
        bin.install "ace-dt"
        generate_completions_from_executable(bin/"ace-dt", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"ace-dt", "gendocs", "man", "."
          man1.install Dir["*.1"]
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/act3-ai/data-tool/releases/download/v1.15.32/ace-dt-v1.15.32-darwin-arm64.tar.gz"
      sha256 "04b209af9657c1f6786f9e8c67f805ce374ca0b0d841c2e4d5dc9f794318349b"

      def install
        bin.install "ace-dt"
        generate_completions_from_executable(bin/"ace-dt", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"ace-dt", "gendocs", "man", "."
          man1.install Dir["*.1"]
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/data-tool/releases/download/v1.15.32/ace-dt-v1.15.32-linux-amd64.tar.gz"
        sha256 "fb338c0ee660a9f4c11babaa5900b8bd0a904162ed523f327f849af739745fb2"

        def install
          bin.install "ace-dt"
          generate_completions_from_executable(bin/"ace-dt", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"ace-dt", "gendocs", "man", "."
            man1.install Dir["*.1"]
          end
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/data-tool/releases/download/v1.15.32/ace-dt-v1.15.32-linux-arm64.tar.gz"
        sha256 "1f4a1251eaaa9f07aade129f7de7b2f442d15b019b3d21c627c3363282121ca0"

        def install
          bin.install "ace-dt"
          generate_completions_from_executable(bin/"ace-dt", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"ace-dt", "gendocs", "man", "."
            man1.install Dir["*.1"]
          end
        end
      end
    end
  end

  test do
    system "#{bin}/ace-dt version"
  end
end
