# frozen_string_literal: true

require_relative "../lib/registry_download"

class AceDt < Formula
  desc "ACE Data Tool"
  homepage "https://git.act3-ace.com/ace/data/tool"
  version "1.15.6"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/data/tool/releases/ace-dt@sha256:ff99a3e8afcc5219c3f5271ca19167c59e9e28794d3fb1748ba5977b5ee502a6",
          using: BlobDownloadStrategy
      sha256 "ff99a3e8afcc5219c3f5271ca19167c59e9e28794d3fb1748ba5977b5ee502a6"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/ace/data/tool/releases/ace-dt@sha256:2f9863fa82b1f1b82711f2bade09548062b23bfc4f12f593d20620d289bf1670",
          using: BlobDownloadStrategy
      sha256 "2f9863fa82b1f1b82711f2bade09548062b23bfc4f12f593d20620d289bf1670"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/ace/data/tool/releases/ace-dt@sha256:c58a850d6f6cbc78429097f6b9d4ae1197736400b5e195f555994a25a58ef58c",
          using: BlobDownloadStrategy
      sha256 "c58a850d6f6cbc78429097f6b9d4ae1197736400b5e195f555994a25a58ef58c"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/data/tool/releases/ace-dt@sha256:3abb1a692f6031a5e68045a5d4a6921de104fad3f5557682f6f12920c92df4b1",
          using: BlobDownloadStrategy
      sha256 "3abb1a692f6031a5e68045a5d4a6921de104fad3f5557682f6f12920c92df4b1"
    end
  end

  def install
    bin.install "ace-dt"
    generate_completions_from_executable(bin/"ace-dt", "completion")

    # Generate manpages
    mkdir "man" do
      system bin/"ace-dt", "gendocs", "man", "."
      man1.install Dir["*.1"]
      man5.install Dir["*.5"]
    end

    # Generate JSON Schema definitions
    # Use pkgetc here so path doesn't change over version numbers
    # Cannot use symlink for this because VS Code cannot follow symlinks for schema files
    mkdir pkgetc do
      system bin/"ace-dt", "genschema", "."
    end
  end

  def caveats
    <<~EOS
      Add the following to VS Code's settings.json file to enable YAML file validation:
        "yaml.schemas": {
          "file://#{pkgetc}/config.dt.act3-ace.io.schema.json": [
            "ace-dt-config.yaml",
            "ace/dt/config.yaml"
          ],
          "file://#{pkgetc}/data.act3-ace.io.schema.json": "entry.yaml"
        }

      Add the following to VS Code's settings.json file to enable JSON file validation:
        "json.schemas": [
          {
            "fileMatch": [
              "entry.json"
            ],
            "url": "file://#{pkgetc}/data.act3-ace.io.schema.json"
          }
        ]

      Check out the quick start guide to get started with ace-dt:
        ace-dt info quick-start-guide
    EOS
  end

  test do
    system "#{bin}/ace-dt", "version"
  end
end
