# frozen_string_literal: true

require_relative "../lib/registry_download"

class Act3Pt < Formula
  desc "ACT3 Project Tool - ACT3's project management toolbox"
  homepage "https://git.act3-ace.com/devsecops/act3-pt"
  version "2.0.0"

  depends_on "glab"
  depends_on "typst"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:93f2cf0e6eee500a4bc87afbe17b0e7ce99c6b97b374407e7512b4b8171558dd",
          using: BlobDownloadStrategy
      sha256 "93f2cf0e6eee500a4bc87afbe17b0e7ce99c6b97b374407e7512b4b8171558dd"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:bb0c93b00417e2bb915ed327def8945e65bb38b0fb636e25671f57cf59993ea0",
          using: BlobDownloadStrategy
      sha256 "bb0c93b00417e2bb915ed327def8945e65bb38b0fb636e25671f57cf59993ea0"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:3d9a3de6c40252eaf410cece1b3cf85093c43a60f06d3854a1a833c04094ac7b",
          using: BlobDownloadStrategy
      sha256 "3d9a3de6c40252eaf410cece1b3cf85093c43a60f06d3854a1a833c04094ac7b"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:ec749bdb51e797e2e4a49d49fa468705e0168e4eb7767c8227ef0f09edf92aa0",
          using: BlobDownloadStrategy
      sha256 "ec749bdb51e797e2e4a49d49fa468705e0168e4eb7767c8227ef0f09edf92aa0"
    end
  end

  conflicts_with "act3-pt-beta", because: "act3-pt and act3-pt-beta install conflicting executables"

  def install
    bin.install "act3-pt"
    generate_completions_from_executable(bin/"act3-pt", "completion")

    # Generate manpages
    mkdir "man" do
      system bin/"act3-pt", "gendocs", "man", "."
      man1.install Dir["*.1"]
      man5.install Dir["*.5"]
    end

    # Generate JSON Schema definitions
    # Use pkgetc here so path doesn't change over version numbers
    # Cannot use symlink for this because VS Code cannot follow symlinks for schema files
    mkdir pkgetc do
      system bin/"act3-pt", "genschema", "."
    end
  end

  def caveats
    <<~EOS
      Add the following to VS Code's settings.json file to enable YAML file validation:
        "yaml.schemas": {
          "file://#{pkgetc}/project.act3-ace.io.schema.json": [
            ".project.yaml",
            ".act3-pt.yaml",
            ".blueprint.yaml",
            ".act3-template.yaml",
            ".blueprintcatalog.yaml",
            "catalog.yaml"
          ],
          "file://#{pkgetc}/pt.act3-ace.io.schema.json": [
            "act3-pt-config.yaml",
            "act3/pt/config.yaml"
          ]
        }

      Check out the quick start guide to get started with act3-pt:
        act3-pt info quick-start-guide
    EOS
  end

  test do
    system "#{bin}/act3-pt", "version"
  end
end
