# frozen_string_literal: true

require_relative "../lib/registry_download"

class Act3Pt < Formula
  desc "ACT3 Project Tool - ACT3's project management toolbox"
  homepage "https://git.act3-ace.com/devsecops/act3-pt"
  version "2.1.0"

  depends_on "glab"
  depends_on "typst"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:e4fe37321c60a23c1489b1a27013bf1dee99b46491a6dd264956431e5dd6edb2",
          using: BlobDownloadStrategy
      sha256 "e4fe37321c60a23c1489b1a27013bf1dee99b46491a6dd264956431e5dd6edb2"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:15622b0c93eb0987506920a0bcc7e6b87d44d6333a974337dc4c04a1d1b1d5b2",
          using: BlobDownloadStrategy
      sha256 "15622b0c93eb0987506920a0bcc7e6b87d44d6333a974337dc4c04a1d1b1d5b2"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:688b76c4581bcea0c1891acf27402ea512026f6db02ecf17ef8c787fef0332a8",
          using: BlobDownloadStrategy
      sha256 "688b76c4581bcea0c1891acf27402ea512026f6db02ecf17ef8c787fef0332a8"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/devsecops/act3-pt/releases/act3-pt@sha256:2d3e0fcf9e586d4f03e17d2a755eb009ffc4dab40d7e7cdfe4c82e39bea07b46",
          using: BlobDownloadStrategy
      sha256 "2d3e0fcf9e586d4f03e17d2a755eb009ffc4dab40d7e7cdfe4c82e39bea07b46"
    end
  end

  conflicts_with "act3-pt-beta", because: "act3-pt and act3-pt-beta install conflicting executables"

  def install
    bin.install "act3-pt"
    generate_completions_from_executable(bin/"act3-pt", "completion")

    # Generate manpages
    mkdir "man" do
      system bin/"act3-pt", "gendocs", "man", "."
      man1.install Dir["*.1"]
      man5.install Dir["*.5"]
    end

    # Generate JSON Schema definitions
    # Use pkgetc here so path doesn't change over version numbers
    # Cannot use symlink for this because VS Code cannot follow symlinks for schema files
    mkdir pkgetc do
      system bin/"act3-pt", "genschema", "."
    end
  end

  def caveats
    <<~EOS
      Add the following to VS Code's settings.json file to enable YAML file validation:
        "yaml.schemas": {
          "file://#{pkgetc}/project.act3-ace.io.schema.json": [
            ".project.yaml",
            ".act3-pt.yaml",
            ".blueprint.yaml",
            ".act3-template.yaml",
            ".blueprintcatalog.yaml",
            "catalog.yaml"
          ],
          "file://#{pkgetc}/pt.act3-ace.io.schema.json": [
            "act3-pt-config.yaml",
            "act3/pt/config.yaml"
          ]
        }

      Check out the quick start guide to get started with act3-pt:
        act3-pt info quick-start-guide
    EOS
  end

  test do
    system "#{bin}/act3-pt", "version"
  end
end
