# frozen_string_literal: true

require_relative "../lib/registry_download"

class AsceHubCli < Formula
  desc "CLI for interacting with ACE Hub"
  homepage "https://git.act3-ace.com/ace/hub/cli"
  version "0.1.3"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:3e33e7f69cda8b88815c17fff4ecb9c0302573d32f814fab32cbc5994f17697b",
          using: BlobDownloadStrategy
      sha256 "3e33e7f69cda8b88815c17fff4ecb9c0302573d32f814fab32cbc5994f17697b"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:2a656e99bd2b86cd58818f4a98da9cd30a66afa56683bf58ba77a52f4d79a214",
          using: BlobDownloadStrategy
      sha256 "2a656e99bd2b86cd58818f4a98da9cd30a66afa56683bf58ba77a52f4d79a214"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:4d09af0fc354be1c98c0f5ff56e5bc5738d7a016582abf0b5b8a05dcd8589fc1",
          using: BlobDownloadStrategy
      sha256 "4d09af0fc354be1c98c0f5ff56e5bc5738d7a016582abf0b5b8a05dcd8589fc1"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:f77bbc80f7a4869b4d680204f7ee628f7d9e72cd4a898240d68e77e661d6d249",
          using: BlobDownloadStrategy
      sha256 "f77bbc80f7a4869b4d680204f7ee628f7d9e72cd4a898240d68e77e661d6d249"
    end
  end

  def install
    bin.install "hub"

    with_homebrew_path do
      # Completions from downstream tools are sourced by asce,
      # so they must be discoverable on the PATH
      generate_completions_from_executable(bin/"hub", "completion")
    end

    # Generate manpages
    mkdir "man" do
      system bin/"hub", "gendocs", "man", "."
      man1.install Dir["*.1"]
      # man5.install Dir["*.5"]
    end
  end

  # test do
  #   system "#{bin}/hub", "version"
  # end
end
