# frozen_string_literal: true

require_relative "../lib/registry_download"

class Asce < Formula
  desc "CLI for managing all things ASCE"
  homepage "https://git.act3-ace.com/ace/cli"
  version "0.1.7"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:26ae87299fd42c8eaf852ea6c778d86c1b0db5aa955186b062a22c9015a7562d",
          using: BlobDownloadStrategy
      sha256 "26ae87299fd42c8eaf852ea6c778d86c1b0db5aa955186b062a22c9015a7562d"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:3fad23443eca15ae8dd62a19c68aa66b9d580be530b649912aa34622f26b575d",
          using: BlobDownloadStrategy
      sha256 "3fad23443eca15ae8dd62a19c68aa66b9d580be530b649912aa34622f26b575d"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:5670b88bba91b7427cadd85e9655447c633d5a9cab53d3b41dafa457d7988129",
          using: BlobDownloadStrategy
      sha256 "5670b88bba91b7427cadd85e9655447c633d5a9cab53d3b41dafa457d7988129"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:4fb0eabd9606358381da779e1656cd0a65e7d2bd6b06a8aa69e241c3de171085",
          using: BlobDownloadStrategy
      sha256 "4fb0eabd9606358381da779e1656cd0a65e7d2bd6b06a8aa69e241c3de171085"
    end
  end

  def install
    bin.install "asce"
    # generate_completions_from_executable(bin/"asce", "completion")

    # # Generate manpages
    # mkdir "man" do
    #   system bin/"asce", "gendocs", "man", "."
    #   man1.install Dir["*.1"]
    #   man5.install Dir["*.5"]
    # end

    # # Generate JSON Schema definitions
    # # Use pkgetc here so path doesn't change over version numbers
    # # Cannot use symlink for this because VS Code cannot follow symlinks for schema files
    # mkdir pkgetc do
    #   system bin/"asce", "genschema", "."
    # end
  end

  test do
    system "#{bin}/asce", "version"
  end
end
