# frozen_string_literal: true

require_relative "../lib/registry_download"

class Asce < Formula
  desc "CLI for managing all things ASCE"
  homepage "https://git.act3-ace.com/ace/cli"
  version "0.1.6"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:b126b42a665145138f13a03255b38b3d30eacb8e4c1e2655f57ff11d7790dc97",
          using: BlobDownloadStrategy
      sha256 "b126b42a665145138f13a03255b38b3d30eacb8e4c1e2655f57ff11d7790dc97"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:e321faaeb46b9dec883536b360094e221cb37eb2160e1087c304cf9adcdd656b",
          using: BlobDownloadStrategy
      sha256 "e321faaeb46b9dec883536b360094e221cb37eb2160e1087c304cf9adcdd656b"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:797fcc503e5c45bdeafa02e70c6a45e39fd180901243f70943ec7488fa088266",
          using: BlobDownloadStrategy
      sha256 "797fcc503e5c45bdeafa02e70c6a45e39fd180901243f70943ec7488fa088266"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/cli/releases/asce@sha256:fa91b1c53107e27d0c3b498806f88863bc4217e33d6d0c95370d821557ad8d90",
          using: BlobDownloadStrategy
      sha256 "fa91b1c53107e27d0c3b498806f88863bc4217e33d6d0c95370d821557ad8d90"
    end
  end

  def install
    bin.install "asce"
    # generate_completions_from_executable(bin/"asce", "completion")

    # # Generate manpages
    # mkdir "man" do
    #   system bin/"asce", "gendocs", "man", "."
    #   man1.install Dir["*.1"]
    #   man5.install Dir["*.5"]
    # end

    # # Generate JSON Schema definitions
    # # Use pkgetc here so path doesn't change over version numbers
    # # Cannot use symlink for this because VS Code cannot follow symlinks for schema files
    # mkdir pkgetc do
    #   system bin/"asce", "genschema", "."
    # end
  end

  test do
    system "#{bin}/asce", "version"
  end
end
