# frozen_string_literal: true

require_relative "../lib/registry_download"

class AsceHubCli < Formula
  desc "CLI for interacting with ACE Hub"
  homepage "https://git.act3-ace.com/ace/hub/cli"
  version "0.1.2"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:25f09834daf03649f9c262d4ea49a83695f400e7a0363244bfd3ef13557b6c71",
          using: BlobDownloadStrategy
      sha256 "25f09834daf03649f9c262d4ea49a83695f400e7a0363244bfd3ef13557b6c71"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:74f398a6fd8e3208fdf2f5e7b714663435382cdf0bd9cabbf9da595860a8511c",
          using: BlobDownloadStrategy
      sha256 "74f398a6fd8e3208fdf2f5e7b714663435382cdf0bd9cabbf9da595860a8511c"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:1da38e1734006cd86beec5b6237d420fb8cc1609ad6fb930e3ab623a077e50cf",
          using: BlobDownloadStrategy
      sha256 "1da38e1734006cd86beec5b6237d420fb8cc1609ad6fb930e3ab623a077e50cf"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/hub/cli/releases/hub@sha256:35b4986dc6d85ffc8b2a459ead964e7d3dbff77f1ff7fc5dbad183436c4cec69",
          using: BlobDownloadStrategy
      sha256 "35b4986dc6d85ffc8b2a459ead964e7d3dbff77f1ff7fc5dbad183436c4cec69"
    end
  end

  def install
    bin.install "hub"

    # with_homebrew_path do
    #   # Completions from downstream tools are sourced by asce,
    #   # so they must be discoverable on the PATH
    #   generate_completions_from_executable(bin/"hub", "completion")
    # end

    # # Generate manpages
    # mkdir "man" do
    #   system bin/"hub", "gendocs", "man", "."
    #   man1.install Dir["*.1"]
    #   # man5.install Dir["*.5"]
    # end
  end

  # test do
  #   system "#{bin}/hub", "version"
  # end
end
