# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hops < Formula
  desc "Homebrew Bottle installer with a focus on performance and mobility."
  homepage "https://github.com/act3-ai/hops"
  version "0.2.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/act3-ai/hops/releases/download/v0.2.3/hops_darwin_amd64.tar.gz"
      sha256 "14e29e17cf67cb1ec5d995239321259aff66e16a6dbd910bae063410c025aceb"

      def install
        bin.install "bin/hops"
        generate_completions_from_executable(bin/"hops", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"hops", "gendocs", "man", "."
          man1.install Dir["*.1"]
          # man5.install Dir["*.5"]
        end
      end
    end
    on_arm do
      url "https://github.com/act3-ai/hops/releases/download/v0.2.3/hops_darwin_arm64.tar.gz"
      sha256 "361657c89fecb474321c8143ab2e26afe59dc2c31b5285c036aa09bc5bb24ee3"

      def install
        bin.install "bin/hops"
        generate_completions_from_executable(bin/"hops", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"hops", "gendocs", "man", "."
          man1.install Dir["*.1"]
          # man5.install Dir["*.5"]
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/hops/releases/download/v0.2.3/hops_linux_amd64.tar.gz"
        sha256 "40d3a3615fff504f771ddf7631e90209f3fb5b5ea6eb3702f9577740cdc2a58d"

        def install
          bin.install "bin/hops"
          generate_completions_from_executable(bin/"hops", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"hops", "gendocs", "man", "."
            man1.install Dir["*.1"]
            # man5.install Dir["*.5"]
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/hops/releases/download/v0.2.3/hops_linux_arm64.tar.gz"
        sha256 "59c1131a3317296fa40801feae03ccf16ab3872d2171ccb81fd56de39e29e5f4"

        def install
          bin.install "bin/hops"
          generate_completions_from_executable(bin/"hops", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"hops", "gendocs", "man", "."
            man1.install Dir["*.1"]
            # man5.install Dir["*.5"]
          end
        end
      end
    end
  end

  test do
    system "#{bin}/hops --version"
  end
end
