# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hops < Formula
  desc "Homebrew Bottle installer with a focus on performance and mobility."
  homepage "https://github.com/act3-ai/hops"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/act3-ai/hops/releases/download/v0.2.1/hops_darwin_amd64.tar.gz"
      sha256 "601bb1814809f3f0a427edf81126e6453c0504bd8998118dcfab4bb772195e82"

      def install
        bin.install "bin/hops"
        generate_completions_from_executable(bin/"hops", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"hops", "gendocs", "man", "."
          man1.install Dir["*.1"]
          # man5.install Dir["*.5"]
        end
      end
    end
    on_arm do
      url "https://github.com/act3-ai/hops/releases/download/v0.2.1/hops_darwin_arm64.tar.gz"
      sha256 "72f20aa449d92c2633f95be2f06a8cc4d2d8aca5081cd8ece29a8f48d050a697"

      def install
        bin.install "bin/hops"
        generate_completions_from_executable(bin/"hops", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"hops", "gendocs", "man", "."
          man1.install Dir["*.1"]
          # man5.install Dir["*.5"]
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/hops/releases/download/v0.2.1/hops_linux_amd64.tar.gz"
        sha256 "53593f05700a747abc1bfdd2a593e65835b1d5fa43517157d7ac807bd388e9e9"

        def install
          bin.install "bin/hops"
          generate_completions_from_executable(bin/"hops", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"hops", "gendocs", "man", "."
            man1.install Dir["*.1"]
            # man5.install Dir["*.5"]
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/hops/releases/download/v0.2.1/hops_linux_arm64.tar.gz"
        sha256 "cc2d263194ea3dea48782ab037ef44e57fe57c2fecc53b64c31e5626f2e2ad6d"

        def install
          bin.install "bin/hops"
          generate_completions_from_executable(bin/"hops", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"hops", "gendocs", "man", "."
            man1.install Dir["*.1"]
            # man5.install Dir["*.5"]
          end
        end
      end
    end
  end

  test do
    system "#{bin}/hops --version"
  end
end
