# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hops < Formula
  desc "Homebrew Bottle installer with a focus on performance and mobility."
  homepage "https://github.com/act3-ai/hops"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/act3-ai/hops/releases/download/v0.1.3/hops_darwin_amd64.tar.gz"
      sha256 "fc98c0dc039c7c3e0f7035c466dedbc10ba1aaa3ba41c2ab12f64be6bfa78708"

      def install
        bin.install "bin/hops"
        generate_completions_from_executable(bin/"hops", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"hops", "gendocs", "man", "."
          man1.install Dir["*.1"]
          # man5.install Dir["*.5"]
        end
      end
    end
    on_arm do
      url "https://github.com/act3-ai/hops/releases/download/v0.1.3/hops_darwin_arm64.tar.gz"
      sha256 "286764d1e96e9a10a347500834d7d78bbd9355af74b60eb26c88742e1a0f1aa9"

      def install
        bin.install "bin/hops"
        generate_completions_from_executable(bin/"hops", "completion")

        # Generate manpages
        mkdir "man" do
          system bin/"hops", "gendocs", "man", "."
          man1.install Dir["*.1"]
          # man5.install Dir["*.5"]
        end
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/hops/releases/download/v0.1.3/hops_linux_amd64.tar.gz"
        sha256 "93cb941da79187a7240a98bcd0aa5081f68b67992502defac8afd288a84731fd"

        def install
          bin.install "bin/hops"
          generate_completions_from_executable(bin/"hops", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"hops", "gendocs", "man", "."
            man1.install Dir["*.1"]
            # man5.install Dir["*.5"]
          end
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/act3-ai/hops/releases/download/v0.1.3/hops_linux_arm64.tar.gz"
        sha256 "a4d2938e6371a1403ff7eeb6b8672adb9ea0879abfde919ad035a15f0c97fb11"

        def install
          bin.install "bin/hops"
          generate_completions_from_executable(bin/"hops", "completion")

          # Generate manpages
          mkdir "man" do
            system bin/"hops", "gendocs", "man", "."
            man1.install Dir["*.1"]
            # man5.install Dir["*.5"]
          end
        end
      end
    end
  end

  test do
    system "#{bin}/hops --version"
  end
end
