# frozen_string_literal: true

require_relative "../lib/registry_download"

class KubectlEquilibria < Formula
  desc "Kubectl plugin for interacting with ACE Equilibria"
  homepage "https://git.act3-ace.com/ace/equilibria"
  version "0.9.9"

  depends_on "kubernetes-cli"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/equilibria/releases/kubectl-equilibria@sha256:5d4459ef9fbd25f9e1c6e50cd1941f8ef1d91a7a9079977c17a5686b70389de2",
          using: BlobDownloadStrategy
      sha256 "5d4459ef9fbd25f9e1c6e50cd1941f8ef1d91a7a9079977c17a5686b70389de2"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/ace/equilibria/releases/kubectl-equilibria@sha256:d0a9067fdbff87684b67f76d5bf6c9f2f732c1b3c69466a8c72708d83957b0d2",
          using: BlobDownloadStrategy
      sha256 "d0a9067fdbff87684b67f76d5bf6c9f2f732c1b3c69466a8c72708d83957b0d2"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/ace/equilibria/releases/kubectl-equilibria@sha256:a0bcb0623a65e34e19ec481dc465927dae5b81e9854b06061fb0d91e548cee37",
          using: BlobDownloadStrategy
      sha256 "a0bcb0623a65e34e19ec481dc465927dae5b81e9854b06061fb0d91e548cee37"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/equilibria/releases/kubectl-equilibria@sha256:c407c9cc988c7333e2f90cf3bfab420d7b726d2bc84e296961f3b3646024af88",
          using: BlobDownloadStrategy
      sha256 "c407c9cc988c7333e2f90cf3bfab420d7b726d2bc84e296961f3b3646024af88"
    end
  end

  def install
    bin.install "kubectl-equilibria"
    generate_completions_from_executable(bin/"kubectl-equilibria", "completion")

    # # Generate manpages
    # mkdir "man" do
    #   system bin/"kubectl-equilibria", "gendocs", "man", "."
    #   man1.install Dir["*.1"]
    #   # man5.install Dir["*.5"]
    # end
  end

  test do
    system "#{bin}/kubectl-equilibria", "version"
  end
end
