# frozen_string_literal: true

require_relative "../lib/registry_download"

class KubectlEquilibria < Formula
  desc "Kubectl plugin for interacting with ACE Equilibria"
  homepage "https://git.act3-ace.com/ace/equilibria"
  version "0.9.3"

  depends_on "kubernetes-cli"

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_macos do
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/homebrew-ace-tools/formula/kubectl-equilibria@sha256:7a26fe1d2a286a1859c0a8b4dac63695f5a731fe436b854f8f9f48919c85fc8b",
          using: BlobDownloadStrategy
      sha256 "7a26fe1d2a286a1859c0a8b4dac63695f5a731fe436b854f8f9f48919c85fc8b"
    end
    if Hardware::CPU.arm?
      url "reg.git.act3-ace.com/ace/homebrew-ace-tools/formula/kubectl-equilibria@sha256:50b689c3f87bc7c1d21444abeb48ad6be590e00a73245de120baca18246bba9c",
          using: BlobDownloadStrategy
      sha256 "50b689c3f87bc7c1d21444abeb48ad6be590e00a73245de120baca18246bba9c"
    end
  end

  # Generated by https://git.act3-ace.com/ace/homebrew-ace-tools/-/blob/master/bin/formulize.sh
  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "reg.git.act3-ace.com/ace/homebrew-ace-tools/formula/kubectl-equilibria@sha256:c166812c51f78122bd4f8fce0b74ecdc65f06bdea3e72d4acb62d658300ab956",
          using: BlobDownloadStrategy
      sha256 "c166812c51f78122bd4f8fce0b74ecdc65f06bdea3e72d4acb62d658300ab956"
    end
    if Hardware::CPU.intel?
      url "reg.git.act3-ace.com/ace/homebrew-ace-tools/formula/kubectl-equilibria@sha256:00529eb1e44e04753c7c8ec4e9cad75a6de1985f20426f65c2384cc0b6f5ebfb",
          using: BlobDownloadStrategy
      sha256 "00529eb1e44e04753c7c8ec4e9cad75a6de1985f20426f65c2384cc0b6f5ebfb"
    end
  end

  def install
    bin.install "kubectl-equilibria"
    generate_completions_from_executable(bin/"kubectl-equilibria", "completion")

    # # Generate manpages
    # mkdir "man" do
    #   system bin/"kubectl-equilibria", "gendocs", "man", "."
    #   man1.install Dir["*.1"]
    #   # man5.install Dir["*.5"]
    # end
  end

  test do
    system "#{bin}/kubectl-equilibria", "version"
  end
end
