#!/usr/bin/env bash
#:  * `act3-login` [<options>]
#:
#:  Runs ACT3 Login to authenticate to ACT3 services.
#:  ACT3 Login documentation: https://gitlab.com/act3-ai/asce/up/-/tree/main/asce-tools
#:
#:  Acts as a shortcut to run the command:
#:    bash -c "$(curl -fsSL https://gitlab.com/act3-ai/asce/up/-/raw/main/act3-login/act3-login)"
#:
#:      -h, --help                       Show this message.

for option in "$@"; do
	case "${option}" in
	-h | --help)
		brew help act3-login
		exit 0
		;;
	*)
		echo "Invalid option"
		brew help act3-login
		exit 1
		;;
	esac
done

# DBUS_SESSION_BUS_ADDRESS is set to preserve the dbus session 
# for use by secret service password managers.
# This is needed for linux users using secretservice for docker config
export DBUS_SESSION_BUS_ADDRESS="${HOMEBREW_DBUS_SESSION_BUS_ADDRESS}"

############################################################
# Run the dang script
############################################################

bash -c "$(curl -fsSL https://gitlab.com/act3-ai/asce/up/-/raw/main/act3-login/act3-login)"
