#!/usr/bin/env bash
#:  * `install-dod-certs` [<options>]
#:
#:  Downloads and installs the latest DoD CA Certificates.
#:  Acts as a shortcut to run the ACT3 Login command:
#:    bash -c "$(curl -fsSL https://raw.githubusercontent.com/act3-ace/aceup/main/dod-certs/dod-certs)"
#:
#:      -h, --help                       Show this message.

for option in "$@"; do
	case "${option}" in
	*)
		brew help install-dod-certs
		exit $?
		;;
	esac
done

############################################################
# Run the dang script
############################################################

bash -c "$(curl -fsSL https://raw.githubusercontent.com/act3-ace/aceup/main/dod-certs/dod-certs)"
