#!/usr/bin/env bash
#:  * `act3-login` [<options>]
#:
#:  Runs ACT3 Login to authenticate to ACT3 services.
#:
#:  Acts as a shortcut to run the command:
#:    bash -c "$(curl -fsSL https://raw.githubusercontent.com/act3-ace/aceup/main/act3-login/act3-login)"
#:
#:      -h, --help                       Show this message.

for option in "$@"; do
	case "${option}" in
	-h | --help)
		brew help act3-login
		exit 0
		;;
	*)
		echo "Invalid option"
		brew help act3-login
		exit 1
		;;
	esac
done

############################################################
# Run the dang script
############################################################

bash -c "$(curl -fsSL https://raw.githubusercontent.com/act3-ace/aceup/main/act3-login/act3-login)"
