#!/usr/bin/env bash
#:  * `asce-tools` [<options>]
#:
#:  Installs ASCE Tools, common tools for work in ASCE.
#:  ASCE Tools documentation: https://gitlab.com/act3-ai/asce/up/-/tree/main/asce-tools
#:
#:          --no-helm      Skip installing Helm plugins. (default false)
#:          --no-kubectl   Skip installing Kubectl plugins. (default false)
#:          --vscode       Install VS Code extensions. (default false)
#:      -h, --help         Show this message.

# Prints the help text manually
function help() {
	# Simple reimplementation of realpath using bash builtins
	SOURCE=$(
		cd "$(dirname "${BASH_SOURCE[0]}")" || exit
		pwd -P
	)/$(basename "${BASH_SOURCE[0]}")

	# Check if script was run as a Homebrew external command
	# Set command source to reflect the intended use of the script
	if [[ "${SOURCE}" == "${HOMEBREW_PREFIX}"* ]]; then
		SOURCE=$(basename "${SOURCE}")
		# Make sure command has "brew-" prefix
		if [[ "${SOURCE}" == "brew-"* ]]; then
			SOURCE="brew ${SOURCE#brew-}"
		fi
	fi

	cat <<EOF
Usage: ${SOURCE} [options]

Installs common tools for work in ASCE.

        --no-helm      Skip installing Helm plugins. (default false)
        --no-kubectl   Skip installing Kubectl plugins. (default false)
        --vscode       Install VS Code extensions. (default false)
    -h, --help         Show this message.
EOF
}

HELM_PLUGINS="true"
KUBECTL_PLUGINS="true"
VSCODE_EXTS="false"
for option in "$@"; do
	case "${option}" in
	--helm) HELM_PLUGINS="true" ;;
	--kubectl) KUBECTL_PLUGINS="true" ;;
	--vscode) VSCODE_EXTS="true" ;;
	-h | --help)
		help
		exit 0
		;;
	*)
		echo "Invalid option"
		help
		exit 1
		;;
	esac
done

set -e

# Initialize cache directory
CACHE="$(brew --cache)/asce-tools"
[ -e "${CACHE}" ] && rm -rf "${CACHE}"
mkdir -p "${CACHE}"

############################################################
# Homebrew Utility Functions
############################################################
# From https://github.com/Homebrew/brew/blob/92d2cec5fa952c32b544faa04e671099d2dc3ff1/Library/Homebrew/brew.sh#L126

ohai() {
	# Check whether stdout is a tty.
	if [[ -n "${HOMEBREW_COLOR}" || (-t 1 && -z "${HOMEBREW_NO_COLOR}") ]]; then
		echo -e "\\033[34m==>\\033[0m \\033[1m$*\\033[0m" # blue arrow and bold text
	else
		echo "==> $*"
	fi
}

opoo() {
	# Check whether stderr is a tty.
	if [[ -n "${HOMEBREW_COLOR}" || (-t 2 && -z "${HOMEBREW_NO_COLOR}") ]]; then
		echo -ne "\\033[4;33mWarning\\033[0m: " >&2 # highlight Warning with underline and yellow color
	else
		echo -n "Warning: " >&2
	fi
	if [[ $# -eq 0 ]]; then
		cat >&2
	else
		echo "$*" >&2
	fi
}

bold() {
	# Check whether stderr is a tty.
	if [[ -n "${HOMEBREW_COLOR}" || (-t 2 && -z "${HOMEBREW_NO_COLOR}") ]]; then
		echo -e "\\033[1m""$*""\\033[0m"
	else
		echo "$*"
	fi
}

onoe() {
	# Check whether stderr is a tty.
	if [[ -n "${HOMEBREW_COLOR}" || (-t 2 && -z "${HOMEBREW_NO_COLOR}") ]]; then
		echo -ne "\\033[4;31mError\\033[0m: " >&2 # highlight Error with underline and red color
	else
		echo -n "Error: " >&2
	fi
	if [[ $# -eq 0 ]]; then
		cat >&2
	else
		echo "$*" >&2
	fi
}

odie() {
	onoe "$@"
	exit 1
}

# DBUS_SESSION_BUS_ADDRESS is set to preserve the dbus session 
# for use by secret service password managers.
# This is needed for linux users using secretservice for docker config
export DBUS_SESSION_BUS_ADDRESS="${HOMEBREW_DBUS_SESSION_BUS_ADDRESS}"

############################################################
# Run "brew bundle install" on the Brewfiles
############################################################
# Use --verbose flag to include the caveats

# Download Brewfile to the cache directory
curl -o "${CACHE}/Brewfile" -fsSL https://gitlab.com/act3-ai/asce/up/-/raw/main/asce-tools/Brewfile

ohai "Installing Homebrew Formulae with brew bundle"

brew bundle install --verbose --file="${CACHE}/Brewfile"

############################################################
# Install VS Code extensions
############################################################
if [ "${VSCODE_EXTS}" == "true" ]; then
	curl -o "${CACHE}/Brewfile-vscode" -fsSL https://gitlab.com/act3-ai/asce/up/-/raw/main/asce-tools/Brewfile-vscode
	echo
	ohai "Installing VS Code extensions with brew bundle"
	brew bundle install --verbose --file="${CACHE}/Brewfile-vscode"
fi

############################################################
# Install kubectl plugins
############################################################
if [ "${KUBECTL_PLUGINS}" == "true" ]; then
	curl -o "${CACHE}/kubectl-plugins" -fsSL https://gitlab.com/act3-ai/asce/up/-/raw/main/asce-tools/kubectl-plugins
	chmod +x "${CACHE}/kubectl-plugins"
	"${CACHE}/kubectl-plugins"
fi

############################################################
# Install helm plugins
############################################################
if [ "${HELM_PLUGINS}" == "true" ]; then
	curl -o "${CACHE}/helm-plugins" -fsSL https://gitlab.com/act3-ai/asce/up/-/raw/main/asce-tools/helm-plugins
	chmod +x "${CACHE}/helm-plugins"
	"${CACHE}/helm-plugins"
fi
