name: Bump Formula version

on:
  push:
    branches:
      - bump-*-*

jobs:
  bump-formula-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh pr create -B main -H ${{github.ref}} --fill-first --reviewer justenstall -l bump-formula-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
